default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: development_pichabox
  username: saumya
  password: <%= ENV['PICHABOX_DATABASE_PASSWORD'] %>
  port: 5432

test:
  <<: *default
  database: test_pichabox